# Generated by Django 5.1.5 on 2025-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
