# Generated by Django 5.1.5 on 2025-02-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_pais_estado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.pais'),
        ),
    ]
