# Generated by Django 5.1.5 on 2025-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_estado_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(max_length=4),
        ),
    ]
